<?php

/**
 * @file
 * Contains islandora_group_defaults.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function islandora_group_defaults_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the islandora_group_defaults module.
    case 'help.page.islandora_group_defaults':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Default config for Access controle with Group, Group Media') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function islandora_group_defaults_theme() {
  return [
    'islandora_group_defaults' => [
      'render element' => 'children',
    ],
  ];
}
